[package]
name = "clvm-zk-sp1-recursive"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = "5.2.2"
clvm-zk-core = { path = "../../../clvm_zk_core" }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
