# Cargo configuration for separate backend builds

[alias]
# Release builds (primary commands)
risc0 = "build --release --target-dir target/risc0 --no-default-features --features risc0,testing"
sp1 = "build --release --target-dir target/sp1 --no-default-features --features sp1,testing"
mock = "build --release --target-dir target/mock --no-default-features --features mock,testing"

# Test commands
test-risc0 = "test --release --target-dir target/risc0 --no-default-features --features risc0,testing"
test-sp1 = "test --release --target-dir target/sp1 --no-default-features --features sp1,testing"
test-mock = "test --target-dir target/mock --no-default-features --features mock,testing"

# Run commands (use with -- <args>)
run-risc0 = "run --release --target-dir target/risc0 --no-default-features --features risc0,testing"
run-sp1 = "run --release --target-dir target/sp1 --no-default-features --features sp1,testing"
run-mock = "run --target-dir target/mock --no-default-features --features mock,testing"

# Check commands (fast compile check without building)
check-risc0 = "check --target-dir target/risc0 --no-default-features --features risc0,testing"
check-sp1 = "check --target-dir target/sp1 --no-default-features --features sp1,testing"
check-mock = "check --target-dir target/mock --no-default-features --features mock,testing"

# Clippy lints
clippy-risc0 = "clippy --target-dir target/risc0 --no-default-features --features risc0,testing"
clippy-sp1 = "clippy --target-dir target/sp1 --no-default-features --features sp1,testing"
clippy-mock = "clippy --target-dir target/mock --no-default-features --features mock,testing"
