[package]
name = "clvm-risc0-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = "=3.0.4"
clvm-zk-core = { path = "../../../clvm_zk_core", features = ["risc0"] }
borsh = { version = "1.5.7", features = ["derive"] }
# ecdsa signature verification support with risc0 acceleration - use risc0's patched sha2
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", rev = "244dc3b08788f7a4ccce14c66896ae3b4f24c166" }
# BLS signature verification support with RISC0 precompiles
bls12_381 = { git = "https://github.com/risc0/zkcrypto-bls12_381.git", rev = "9ea427c0eb1a7e2ac16902a322aea156c496ddb0", default-features = false, features = ["groups", "pairings", "experimental"] }





